apiVersion: skaffold/v1beta2
kind: Config
build: 
    local:
        push: false
    artifacts:
        - image: ww951206/multi-client
          context: ./client
          docker:
            dockerfile: Dockerfile
          sync:
            '**/*.js': .
            '**/*.css': .
            '**/*.html': .
        - image: ww951206/multi-server
          context: ./server
          docker:
            dockerfile: Dockerfile
          sync:
            '**/*.js': .
        - image: ww951206/multi-worker
          context: ./worker
          docker:
            dockerfile: Dockerfile
          sync:
            '**/*.js': .
           
deploy:
    kubectl:
        manifests:
            - k8s/client-deployment.yaml
            - k8s/server-deployment.yaml
            - k8s/worker-deployment.yaml
            - k8s/client-cluster-ip-service.yaml
            - k8s/server-cluster-ip-service.yaml
