apiVersion: cert-manager.io/v1alpha2
kind: certificate
metadata:
    name:k8s-multi-com-tls
spec:
    secretName: k8s-multi-com
    issuerRef: 
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: tinybubu.com
    # List of all domains associated with this certificate 
    dnsNames:
        - tinybubu.com
        - www.tinybubu.com
    acme:
        config:
            - http01:
                ingressClass: nginx
            # domain letsEncryp wants to confirm and give certificate
            domains:
                - tinybubu.com
                - www.tinybubu.com